# Generated by Django 6.0 on 2026-05-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_daypass'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daypass',
            name='unique_daypass_per_user_per_day',
        ),
        migrations.AddField(
            model_name='attendance',
            name='day_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.daypass'),
        ),
        migrations.AddField(
            model_name='daypass',
            name='name',
            field=models.CharField(default='Walk-in', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='daypass',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_daypass_per_user_per_day'),
        ),
        migrations.RemoveField(
            model_name='daypass',
            name='user',
        ),
    ]
